[package]
name = "core_bin"
version = "0.1.0"
edition = "2024"

[dependencies]
core_lib = { path = "../core_lib" }
service_watcher = { path = "../service_watcher" }

anyhow = "1.0.102"
clap = { version = "4.6.0", features = ["derive", "string"] }
kameo = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = "0.1.44"
tracing-subscriber = { workspace = true, features = ["env-filter"] }
