#![allow(unused)]

pub mod fingerprint;

use sqlx::{FromRow, migrate::Migrator};
use time::OffsetDateTime;

/// Stores the acoustic fingerprint and the resolved metadata ID for a track.
///
/// This record is created immediately after `fpcalc` finishes processing.
#[derive(Debug, Clone, FromRow)]
pub struct TrackFingerprint {
    /// The track ID (Primary Key, Foreign Key to tracks.id)
    pub track_id: i64,

    /// The acoustic fingerprint generated by fpcalc.
    pub chromaprint: String,

    /// The duration of the track calculated by fpcalc.
    pub duration: f64,

    /// The final MusicBrainz Recording ID (MBID).
    /// Is `None` when the track is waiting for User Interaction,
    /// and populated once the interaction is resolved or auto-matched.
    pub matched_mbid: Option<String>,

    /// The exact time fingerprint was calculated.
    pub calculated_at: OffsetDateTime,
}
