use std::path::PathBuf;

use kameo::prelude::Message;

/// Track events generated by background services (e.g., Watcher)
/// and processed by the Coordinator.
pub trait TrackEventHandler: Message<TrackReadyToProcess> + Message<TrackRemoved> {}
impl<T> TrackEventHandler for T where T: Message<TrackReadyToProcess> + Message<TrackRemoved> {}

/// A file has appeared or been updated.
///
/// For the Coordinator, this is a signal to: "check the database, verify the hash,
/// and start processing".
#[derive(Debug, Clone)]
pub struct TrackReadyToProcess(pub PathBuf);

/// A file was removed or renamed (moved out of the watch directory).
///
/// For the Coordinator, this is a signal to: "mark as missing or cancel active tasks".
#[derive(Debug, Clone)]
pub struct TrackRemoved(pub PathBuf);
