use std::path::PathBuf;

use kameo::{Actor, prelude::Message};

/// Sent by an external service to the Coordinator
/// when the user has provided the requested information.
#[derive(Debug, Clone)]
pub struct InteractionResolved {
    /// ID of the track.
    pub track_id: i64,

    /// Name of the plugin.
    pub plugin_name: String,

    /// The actual data submitted by the user.
    pub response_payload: serde_json::Value,
}

/// Track events generated by background services (e.g., Watcher)
/// and processed by the Coordinator.
pub trait TrackCoordinator: Actor + Message<TrackReadyToProcess> + Message<TrackRemoved> {}
impl<T> TrackCoordinator for T where T: Actor + Message<TrackReadyToProcess> + Message<TrackRemoved> {}

/// A file has appeared or been updated.
///
/// For the Coordinator, this is a signal to: "check the database, verify the hash,
/// and start processing".
#[derive(Debug, Clone)]
pub struct TrackReadyToProcess(pub PathBuf);

/// A file was removed or renamed (moved out of the watch directory).
///
/// For the Coordinator, this is a signal to: "mark as missing or cancel active tasks".
#[derive(Debug, Clone)]
pub struct TrackRemoved(pub PathBuf);
