use serde::Deserialize;

/// Represents the fingerprint of the track generated by fpcalc.
#[derive(Debug, Deserialize)]
pub struct Fingerprint {
    /// Duration of the track (in seconds), needed for the AcoustID API.
    pub duration: f64,

    /// The actual AcousticID fingerprint string.
    pub fingerprint: String,
}
